export type CountryDefinition = {
  code: string;
  slug: string;
  name: string;
  currency: string;
  flagEmoji: string;
  displayOrder: number;
};

export type EndpointDefinition = {
  slug: string;
  countrySlug: string;
  name: string;
  category: 'Payin' | 'Payout' | 'Checkout' | 'Status' | 'Balance' | 'Verification' | 'Other';
  description: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  defaultQuery?: Record<string, string>;
  defaultHeaders?: Record<string, string>;
  defaultBody?: string;
  requiresSignature: boolean;
  signatureStrategy?: string;
  isMoneyMovement?: boolean;
};

export const INITIAL_COUNTRIES: CountryDefinition[] = [
  {
    code: 'PK',
    slug: 'pkr',
    name: 'Pakistan',
    currency: 'PKR',
    flagEmoji: '🇵🇰',
    displayOrder: 1,
  },
  {
    code: 'BD',
    slug: 'bdt',
    name: 'Bangladesh',
    currency: 'BDT',
    flagEmoji: '🇧🇩',
    displayOrder: 2,
  },
  {
    code: 'ID',
    slug: 'idr',
    name: 'Indonesia',
    currency: 'IDR',
    flagEmoji: '🇮🇩',
    displayOrder: 3,
  },
  {
    code: 'PH',
    slug: 'php',
    name: 'Philippines',
    currency: 'PHP',
    flagEmoji: '🇵🇭',
    displayOrder: 4,
  },
];

export const INITIAL_ENDPOINTS: EndpointDefinition[] = [
  // --- PAKISTAN (PKR) ENDPOINTS ---
  {
    slug: 'pkr-payin',
    countrySlug: 'pkr',
    name: 'H2H Payin API (Async)',
    category: 'Payin',
    description: 'Direct host-to-host payin initiation. Immediate pending response; final status delivered via webhook.',
    method: 'POST',
    path: '/api/payments',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        orderId: 'ORD1999',
        amount: 10,
        branchCode: 'BR-002',
        paymentMethodName: 'JazzCash',
        customerContact: '03273595453',
        customerName: 'Bilal',
        customerEmail: 'ali@example.com',
        callbackUrl: '',
      },
      null,
      2
    ),
  },
  {
    slug: 'pkr-zindigi-confirm',
    countrySlug: 'pkr',
    name: 'Zindigi OTP Confirm API',
    category: 'Verification',
    description: 'Confirms Zindigi H2H payin using customer OTP received via SMS.',
    method: 'POST',
    path: '/api/payments/zindigi/confirm',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        otp: '26676',
        orderId: 'OR1901',
      },
      null,
      2
    ),
  },
  {
    slug: 'pkr-sync-payin',
    countrySlug: 'pkr',
    name: 'H2H Payin API (Sync)',
    category: 'Payin',
    description: 'Synchronous payin where response is returned after user action approval.',
    method: 'POST',
    path: '/api/sync/payments',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        orderId: 'ORD1999',
        amount: 10,
        branchCode: 'BR-002',
        paymentMethodName: 'JazzCash',
        customerContact: '03273595453',
        customerName: 'Bilal',
        customerEmail: 'ali@example.com',
        callbackUrl: '',
      },
      null,
      2
    ),
  },
  {
    slug: 'pkr-checkout',
    countrySlug: 'pkr',
    name: 'Checkout Session API',
    category: 'Checkout',
    description: 'Generates a unique hosted checkout session URL for customer-initiated payments.',
    method: 'POST',
    path: '/api/checkout/sessions',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        orderId: 'ORD1137a9970163',
        branchCode: '123000',
        amount: 1,
        paymentMethodName: 'jazzcash',
        customerContact: '03409583505',
        customerEmail: 'buyer@example.com',
        callbackUrl: 'https://merchant.com/webhook',
        customerName: 'Buyer Name',
        successUrl: 'https://merchant.com/success',
        failedUrl: 'https://merchant.com/failed',
        pendingUrl: 'https://merchant.com/pending',
        expiresInSeconds: 600,
      },
      null,
      2
    ),
  },
  {
    slug: 'pkr-payin-status',
    countrySlug: 'pkr',
    name: 'Payin Status Inquiry',
    category: 'Status',
    description: 'Query status of a payin transaction. Excluded from signature in AssanPay specification.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payin',
      orderId: 'ORD1301',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'pkr-payout',
    countrySlug: 'pkr',
    name: 'H2H Payout API',
    category: 'Payout',
    description: 'Initiate wallet or IBFT bank payout disbursement from merchant balance.',
    method: 'POST',
    path: '/api/merchant/wallet-payouts',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        amount: 1000,
        branchCode: 'BR-002',
        orderId: 'ORDPAYOUT1001',
        bankCode: '59',
        accountNo: '03273595453',
        purpose: 'Settlement',
        cnic: '4200000000000',
        phone: '03330000000',
        callbackUrl: 'https://merchant.com/webhook',
      },
      null,
      2
    ),
  },
  {
    slug: 'pkr-payout-status',
    countrySlug: 'pkr',
    name: 'Payout Status Inquiry',
    category: 'Status',
    description: 'Query status of an IBFT or mobile wallet payout. Excluded from signature.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payout',
      orderId: 'ORDPAYOUT1001',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'pkr-balance',
    countrySlug: 'pkr',
    name: 'Balance Check API',
    category: 'Balance',
    description: 'Check available and ledger balances across PKR merchant branches.',
    method: 'GET',
    path: '/api/merchant/balance/h2h',
    requiresSignature: true,
    defaultBody: '',
  },

  // --- BANGLADESH (BDT) ENDPOINTS ---
  {
    slug: 'bdt-checkout',
    countrySlug: 'bdt',
    name: 'Create Checkout Session',
    category: 'Checkout',
    description: 'Hosted P2C / P2P checkout page. Amount must be a whole integer in BDT.',
    method: 'POST',
    path: '/api/checkout/sessions',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        mode: 'P2C',
        paymentMethodName: 'bkash',
        amount: 500,
        currency: 'BDT',
        orderId: 'ORD-12345',
        branchCode: '123456',
        customerName: 'Rahim Uddin',
        customerEmail: 'rahim@example.com',
        customerContact: '01700000000',
        callbackUrl: 'https://merchant.com/webhooks/assanpay',
        successUrl: 'https://merchant.com/thank-you',
        failedUrl: 'https://merchant.com/failed',
        pendingUrl: 'https://merchant.com/pending',
      },
      null,
      2
    ),
  },
  {
    slug: 'bdt-payin',
    countrySlug: 'bdt',
    name: 'H2H Payin API',
    category: 'Payin',
    description: 'Direct host-to-host payin. In P2P mode, returns walletNumber for the customer to push money.',
    method: 'POST',
    path: '/api/payments',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        paymentMethodName: 'bkash',
        mode: 'P2P',
        amount: 500,
        currency: 'BDT',
        orderId: 'ORD-12345',
        branchCode: '123456',
        customerContact: '01700000000',
        customerName: 'Rahim Uddin',
        customerEmail: 'rahim@example.com',
        callbackUrl: 'https://merchant.com/webhooks/assanpay',
      },
      null,
      2
    ),
  },
  {
    slug: 'bdt-trx-submit',
    countrySlug: 'bdt',
    name: 'Submit P2P TrxID API',
    category: 'Verification',
    description: 'Submit customer wallet transaction reference (TrxID) after P2P transfer.',
    method: 'POST',
    path: '/api/payments/p2p/submit',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        orderId: 'ORD-12345',
        trxId: '75COJ0K0',
      },
      null,
      2
    ),
  },
  {
    slug: 'bdt-payin-status',
    countrySlug: 'bdt',
    name: 'Payin Status Inquiry',
    category: 'Status',
    description: 'Query payment state. Excluded from signature in AssanPay documentation.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payin',
      orderId: 'ORD-12345',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'bdt-payout',
    countrySlug: 'bdt',
    name: 'H2H Payout API',
    category: 'Payout',
    description: 'Disburse funds to a Bangladesh wallet (Bkash or Nagad). Amount must be an integer.',
    method: 'POST',
    path: '/api/merchant/wallet-payouts',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        method: 'Bkash',
        mode: 'P2P',
        amount: 1000,
        accountNo: '01711111111',
        branchCode: '123456',
        orderId: 'PO-98765',
        beneficiaryName: 'Karim',
        callbackUrl: 'https://merchant.com/webhooks/assanpay-payout',
      },
      null,
      2
    ),
  },
  {
    slug: 'bdt-payout-status',
    countrySlug: 'bdt',
    name: 'Payout Status Inquiry',
    category: 'Status',
    description: 'Query payout state. Excluded from signature in AssanPay documentation.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payout',
      orderId: 'PO-98765',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'bdt-balance',
    countrySlug: 'bdt',
    name: 'Balance Check API',
    category: 'Balance',
    description: 'Read P2C and P2P balance pools for Bangladesh merchant.',
    method: 'GET',
    path: '/api/merchant/balance/h2h',
    requiresSignature: true,
    defaultBody: '',
  },

  // --- INDONESIA (IDR) ENDPOINTS ---
  {
    slug: 'idr-checkout-session',
    countrySlug: 'idr',
    name: 'Checkout Session API',
    category: 'Checkout',
    description: 'Hosted checkout page for customer-initiated pay-ins (QRIS, OVO, DANA, GOPAY, LINKAJA, SHOPEEPAY, VA).',
    method: 'POST',
    path: '/api/checkout/sessions',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        orderId: 'ORD-100001',
        amount: 50000,
        currency: 'IDR',
        branchCode: 'BR001',
        customerName: 'Budi Santoso',
        customerEmail: 'budi@example.com',
        customerContact: '081234567890',
        callbackUrl: 'https://merchant.example.com/webhooks/assanpay',
        successUrl: 'https://merchant.example.com/checkout/success',
        failedUrl: 'https://merchant.example.com/checkout/failed',
        pendingUrl: 'https://merchant.example.com/checkout/pending',
        expiresInSeconds: 600,
        paymentMethodName: 'QRIS',
      },
      null,
      2
    ),
  },
  {
    slug: 'idr-checkout-session-encrypted',
    countrySlug: 'idr',
    name: 'Checkout Session Encrypted API',
    category: 'Checkout',
    description: 'AES-256-GCM encrypted checkout payload — signature computed over final ciphertext body.',
    method: 'POST',
    path: '/api/checkout/sessions',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        encrypted: true,
        alg: 'AES/GCM',
        iv: 'vXFGUThmJYdsNrkc',
        cipherText: '9TdgmZv_Fvj_mecL...',
      },
      null,
      2
    ),
  },
  {
    slug: 'idr-h2h-payin',
    countrySlug: 'idr',
    name: 'H2H Pay-in API',
    category: 'Payin',
    description: 'Server-to-server direct pay-in. Returns qrPayload for QRIS, redirectUrl for e-wallets, or vaNumber for VA.',
    method: 'POST',
    path: '/api/payments',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        branchCode: 'BR001',
        paymentMethodName: 'QRIS',
        amount: 50000,
        currency: 'IDR',
        orderId: 'ORD-100001',
        customerContact: '081234567890',
        customerName: 'Budi Santoso',
        customerEmail: 'budi@example.com',
        callbackUrl: 'https://merchant.example.com/webhooks/assanpay',
      },
      null,
      2
    ),
  },
  {
    slug: 'idr-h2h-payin-encrypted',
    countrySlug: 'idr',
    name: 'H2H Pay-in Encrypted API',
    category: 'Payin',
    description: 'AES-256-GCM encrypted direct host-to-host pay-in.',
    method: 'POST',
    path: '/api/payments',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        encrypted: true,
        alg: 'AES/GCM',
        iv: 'vXFGUThmJYdsNrkc',
        cipherText: '9TdgmZv_Fvj_mecL...',
      },
      null,
      2
    ),
  },
  {
    slug: 'idr-payin-status',
    countrySlug: 'idr',
    name: 'Pay-in Status Inquiry',
    category: 'Status',
    description: 'Query pay-in status by order ID. Exempt from HMAC signature; requires X-API-KEY only.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payin',
      orderId: 'ORD-100001',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'idr-h2h-payout',
    countrySlug: 'idr',
    name: 'H2H Payout API',
    category: 'Payout',
    description: 'Disburse funds to beneficiary bank or e-wallet (OVO, DANA, GoPay, LinkAja, ShopeePay). Rail auto-selected.',
    method: 'POST',
    path: '/api/merchant/wallet-payouts',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        amount: 75000,
        orderId: 'PO-200045',
        branchCode: 'BR001',
        bankName: 'Bank Central Asia',
        bankCode: '1007',
        accountNo: '1234567890',
        beneficiaryName: 'Siti Rahayu',
        purpose: 'Supplier settlement',
        callbackUrl: 'https://merchant.example.com/webhooks/assanpay',
      },
      null,
      2
    ),
  },
  {
    slug: 'idr-h2h-payout-encrypted',
    countrySlug: 'idr',
    name: 'H2H Payout Encrypted API',
    category: 'Payout',
    description: 'AES-256-GCM encrypted payout disbursement.',
    method: 'POST',
    path: '/api/merchant/wallet-payouts',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        encrypted: true,
        alg: 'AES/GCM',
        iv: 'vXFGUThmJYdsNrkc',
        cipherText: '9TdgmZv_Fvj_mecL...',
      },
      null,
      2
    ),
  },
  {
    slug: 'idr-payout-status',
    countrySlug: 'idr',
    name: 'Payout Status Inquiry',
    category: 'Status',
    description: 'Query payout state by order ID. Exempt from HMAC signature; requires X-API-KEY only.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payout',
      orderId: 'PO-200045',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'idr-balance',
    countrySlug: 'idr',
    name: 'Balance Check API',
    category: 'Balance',
    description: 'Check merchant available and ledger balance pools broken down by branch code.',
    method: 'GET',
    path: '/api/merchant/balance/h2h',
    requiresSignature: true,
    defaultBody: '',
  },

  // --- PHILIPPINES (PHP) ENDPOINTS ---
  {
    slug: 'php-checkout-session',
    countrySlug: 'php',
    name: 'Checkout Session API',
    category: 'Checkout',
    description: 'Hosted checkout page for customer pay-ins (GCASH, GCASHQR, GRABPAY, PAYMAYA, QRPH).',
    method: 'POST',
    path: '/api/checkout/sessions',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        orderId: 'ORD-100001',
        amount: 1500.0,
        currency: 'PHP',
        branchCode: 'BR001',
        customerName: 'Juan Dela Cruz',
        customerEmail: 'juan@example.com',
        customerContact: '09151037551',
        callbackUrl: 'https://merchant.example.com/webhooks/assanpay',
        successUrl: 'https://merchant.example.com/checkout/success',
        failedUrl: 'https://merchant.example.com/checkout/failed',
        pendingUrl: 'https://merchant.example.com/checkout/pending',
        expiresInSeconds: 600,
        paymentMethodName: 'QRPH',
      },
      null,
      2
    ),
  },
  {
    slug: 'php-checkout-session-encrypted',
    countrySlug: 'php',
    name: 'Checkout Session Encrypted API',
    category: 'Checkout',
    description: 'AES-256-GCM encrypted checkout session payload.',
    method: 'POST',
    path: '/api/checkout/sessions',
    requiresSignature: true,
    defaultBody: JSON.stringify(
      {
        encrypted: true,
        alg: 'AES/GCM',
        iv: 'vXFGUThmJYdsNrkc',
        cipherText: '9TdgmZv_Fvj_mecL...',
      },
      null,
      2
    ),
  },
  {
    slug: 'php-h2h-payin',
    countrySlug: 'php',
    name: 'H2H Pay-in API',
    category: 'Payin',
    description: 'Server-to-server payin for QRPH, GRABPAY, PAYMAYA. Returns QR payload for QRPH.',
    method: 'POST',
    path: '/api/payments',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        branchCode: 'BR001',
        paymentMethodName: 'QRPH',
        amount: 1500.0,
        currency: 'PHP',
        orderId: 'ORD-100001',
        customerContact: '09151037551',
        customerName: 'Juan Dela Cruz',
        customerEmail: 'juan@example.com',
        callbackUrl: 'https://merchant.example.com/webhooks/assanpay',
      },
      null,
      2
    ),
  },
  {
    slug: 'php-h2h-payin-encrypted',
    countrySlug: 'php',
    name: 'H2H Pay-in Encrypted API',
    category: 'Payin',
    description: 'AES-256-GCM encrypted server-to-server payin.',
    method: 'POST',
    path: '/api/payments',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        encrypted: true,
        alg: 'AES/GCM',
        iv: 'vXFGUThmJYdsNrkc',
        cipherText: '9TdgmZv_Fvj_mecL...',
      },
      null,
      2
    ),
  },
  {
    slug: 'php-payin-status',
    countrySlug: 'php',
    name: 'Pay-in Status Inquiry',
    category: 'Status',
    description: 'Query pay-in status by order ID. Exempt from HMAC signature; requires X-API-KEY only.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payin',
      orderId: 'ORD-100001',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'php-h2h-payout',
    countrySlug: 'php',
    name: 'H2H Payout API',
    category: 'Payout',
    description: 'Disburse funds to Philippine bank/wallet. Auto-routed: <= PHP 50,000 via InstaPay, > PHP 50,000 via PesoNet.',
    method: 'POST',
    path: '/api/merchant/wallet-payouts',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        amount: 2500.0,
        orderId: 'PO-200045',
        branchCode: 'BR001',
        bankName: 'AllBank',
        bankCode: 'ALLBPHM1',
        accountNo: '1234567890',
        beneficiaryName: 'Maria Santos',
        purpose: 'Supplier settlement',
        callbackUrl: 'https://merchant.example.com/webhooks/assanpay',
      },
      null,
      2
    ),
  },
  {
    slug: 'php-h2h-payout-encrypted',
    countrySlug: 'php',
    name: 'H2H Payout Encrypted API',
    category: 'Payout',
    description: 'AES-256-GCM encrypted payout disbursement.',
    method: 'POST',
    path: '/api/merchant/wallet-payouts',
    requiresSignature: true,
    isMoneyMovement: true,
    defaultBody: JSON.stringify(
      {
        encrypted: true,
        alg: 'AES/GCM',
        iv: 'vXFGUThmJYdsNrkc',
        cipherText: '9TdgmZv_Fvj_mecL...',
      },
      null,
      2
    ),
  },
  {
    slug: 'php-payout-status',
    countrySlug: 'php',
    name: 'Payout Status Inquiry',
    category: 'Status',
    description: 'Query payout state by order ID. Exempt from HMAC signature; requires X-API-KEY only.',
    method: 'GET',
    path: '/api/merchant/status-inquiry',
    defaultQuery: {
      type: 'payout',
      orderId: 'PO-200045',
    },
    requiresSignature: false,
    defaultBody: '',
  },
  {
    slug: 'php-balance',
    countrySlug: 'php',
    name: 'Balance Check API',
    category: 'Balance',
    description: 'Check available balance, ledger balance, and branch breakdowns in PHP.',
    method: 'GET',
    path: '/api/merchant/balance/h2h',
    requiresSignature: true,
    defaultBody: '',
  },
];
